clone_depth: 10

# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "7"
      platform: x86
    - nodejs_version: "8"
      platform: x86


# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # run tests
  - npm test

after_test:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\xmlResults\accessSniff.test.js.xml))
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\xmlResults\jsDom.test.js.xml))
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\xmlResults\logger.test.js.xml))
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\xmlResults\reports.test.js.xml))

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
